pipeline:

  test-builder:
    group: build
    image: plugins/docker
    dockerfile: Dockerfile-builder
    when:
        branch: [ develop, feature/*]
        
  test-runner:
    group: build
    image: plugins/docker
    dockerfile: Dockerfile-runner
    when:
        branch: [ develop, feature/*]

  builder:
    group: build
    image: plugins/docker
    repo: waddle/vapor-builder
    tags: latest
    dockerfile: Dockerfile-builder
    secrets: [ docker_username, docker_password ]
    when:
        branch: master
    
  runner:
    group: build
    image: plugins/docker
    repo: waddle/vapor-runner
    tags: latest
    dockerfile: Dockerfile-runner
    secrets: [ docker_username, docker_password ]
    when:
        branch: master