pipeline:

  test-builder:
    group: test
    image: plugins/docker
    repo: waddle/vapor-builder
    dockerfile: Dockerfile-builder
    secrets: [ docker_username, docker_password ]
    dry_run: true
    when:
        branch: [ develop, feature/*]
        event: push

  test-runner:
    group: test
    image: plugins/docker
    repo: waddle/vapor-builder
    dockerfile: Dockerfile-runner
    secrets: [ docker_username, docker_password ]
    dry_run: true
    when:
        branch: [ develop, feature/*]
        event: push

  builder:
    group: build
    image: plugins/docker
    repo: waddle/vapor-builder
    auto_tag: true
    dockerfile: Dockerfile-builder
    secrets: [ docker_username, docker_password ]
    when:
        branch: master
        event: [push, tag]
            
  runner:
    group: build
    image: plugins/docker
    repo: waddle/vapor-runner
    auto_tag: true
    dockerfile: Dockerfile-runner
    secrets: [ docker_username, docker_password ]
    when:
        branch: master
        event: [push, tag]