pipeline:

  builder:
    group: build
    image: plugins/docker
    repo: waddle/vapor-builder
    tags: latest
    dockerfile: Dockerfile-builder
    secrets: [ docker_username, docker_password ]
    
  runner:
    group: build
    image: plugins/docker
    repo: waddle/vapor-runner
    tags: latest
    dockerfile: Dockerfile-runner
    secrets: [ docker_username, docker_password ]